#!/usr/bin/env python3
'Assigns semantic names and readable metadata to map purposes.\n\nThe names are derived exclusively from the textures and meshes used by\neach asset. The migration preserves aliases for all names generated by\nthe original catalogs and updates the `effectName` of the converted data.\n\nUsage:\n    python tools/normalize_map_effect_assets.py --dry-run\n    python tools/normalize_map_effect_assets.py'

from __future__ import annotations

import argparse
import json
import re
import shutil
from collections import Counter
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
EFFECT_ROOT = DATA_DIR / "effects"
ASSET_DIR = EFFECT_ROOT / "mapeffects"
CATALOG_DIR = EFFECT_ROOT / "catalogs"
ALIAS_PATH = CATALOG_DIR / "map_effect_aliases.json"
NAME_PATH = CATALOG_DIR / "map_effect_names.json"
STAGING_DIR = EFFECT_ROOT / ".map_effect_name_staging"
BACKUP_DIR = EFFECT_ROOT / ".mapeffects_before_name_migration"

PLACEHOLDER_RE = re.compile(r".+_seq_\d+$")
MAP_HASH_RE = re.compile(r"__map_[0-9a-f]+$", re.IGNORECASE)

# From the specific to the general. Compound words are detected before
# their families so that "waterfall" doesn't end up labeled just "water."
SEMANTIC_PATTERNS = (
    ("firefly", ("firefly",)),
    ("waterfall", ("waterfall", "fallwater")),
    ("waterspout", ("waterspout",)),
    ("water_drop", ("waterdrop",)),
    ("water_wave", ("waterwave",)),
    ("rising_water", ("waterrising",)),
    ("fireball", ("fireball",)),
    ("fire_circle", ("firecircle",)),
    ("wood_fire", ("woodfire",)),
    ("fire", ("ofire", "fire")),
    ("lava", ("lava", "magma")),
    ("lamp", ("lamp",)),
    ("torch", ("torch",)),
    ("candle", ("candle",)),
    ("lightning", ("lightning", "thunderbolt")),
    ("electric", ("electric", "elec")),
    ("portal", ("portal", "potal")),
    ("crystal", ("crystal", "cristal", "cryolite")),
    ("magic_square", ("magicsquare",)),
    ("alchemy", ("alchemy",)),
    ("light", ("vollight", "vlight", "lighting", "light", "lig0")),
    ("star", ("star",)),
    ("water", ("water",)),
    ("wave", ("wave", "waver")),
    ("pond", ("pond",)),
    ("bubble", ("bubble", "buble")),
    ("rain", ("rain",)),
    ("snow", ("snow",)),
    ("ice", ("ice",)),
    ("fog", ("fog", "fogy")),
    ("smoke", ("smoke", "smo")),
    ("dust", ("dust", "dirt")),
    ("sand", ("sand",)),
    ("blood", ("blood",)),
    ("leaf", ("leaf",)),
    ("butterfly", ("butterfly",)),
    ("fish", ("fish",)),
    ("fountain", ("fountain",)),
    ("splash", ("splash", "spash")),
    ("water_spray", ("spa00",)),
    ("twister", ("twister", "twistring", "twist")),
    ("ravatron", ("ravatron",)),
    ("ghost", ("ghost",)),
    ("skeleton", ("skeley", "skeleton")),
    ("angel", ("angel",)),
    ("eye", ("eye",)),
    ("smithy", ("smithy",)),
    ("rune", ("rune",)),
    ("event_marker", ("ev_worldcup",)),
    ("world_structure", ("a8_world",)),
    ("dungeon_structure", ("dun002", "r2_dun1_")),
    ("energy_structure", ("shangd",)),
    ("glass", ("glass",)),
    ("statue", ("statue",)),
    ("lotus", ("lotus",)),
    ("tree", ("tree", "wood")),
    ("earth", ("earth",)),
    ("wall", ("gwall", "wall")),
    ("beam", ("invertical", "vertical", "vetical", "horizontal")),
    ("sky", ("sky",)),
    ("aura", ("aura",)),
    ("glow", ("glow",)),
    ("circle", ("circle",)),
    ("sphere", ("sphere",)),
    ("ring", ("ring",)),
    ("particle", ("particle",)),
)

COLOR_PATTERNS = (
    ("blue", ("blue", "bule", "blucore")),
    ("red", ("red",)),
    ("green", ("green",)),
    ("purple", ("purple", "violet")),
    ("yellow", ("yellow", "yellcore")),
    ("black", ("black",)),
    ("white", ("white",)),
)


def _json_text(data: dict) -> str:
    return json.dumps(data, ensure_ascii=False, indent="\t")


def _resource_stem(name: str) -> str:
    return MAP_HASH_RE.sub("", Path(str(name)).stem.lower())


def _semantic_base(names: list[str]) -> str:
    stems = [_resource_stem(name) for name in names if name]
    categories = [
        label for label, needles in SEMANTIC_PATTERNS
        if any(any(needle in stem for needle in needles) for stem in stems)
    ]

    specific_water = {"waterfall", "waterspout", "water_drop",
                      "water_wave", "rising_water"}
    specific_fire = {"firefly", "fireball", "fire_circle", "wood_fire"}
    if specific_water.intersection(categories):
        categories = [item for item in categories
                      if item not in {"water", "wave"}]
    if specific_fire.intersection(categories):
        categories = [item for item in categories if item != "fire"]
    if "lightning" in categories:
        categories = [item for item in categories if item != "light"]
    if "fire_circle" in categories or "magic_square" in categories:
        categories = [item for item in categories if item != "circle"]

    colors = [
        label for label, needles in COLOR_PATTERNS
        if any(any(needle in stem for needle in needles) for stem in stems)
    ]
    chosen = categories[:3]
    if colors and len(chosen) < 3:
        chosen.append(colors[0])
    if chosen:
        return "_".join(chosen)

    for stem in stems:
        cleaned = re.sub(r"[^a-z0-9]+", "_", stem).strip("_")
        cleaned = re.sub(r"\d+", "", cleaned).strip("_")
        cleaned = cleaned.replace("potal", "portal").replace("cristal", "crystal")
        cleaned = cleaned.replace("vetical", "vertical")
        if cleaned and cleaned not in {"mesh", "effect"}:
            return cleaned[:48]
    return "map_effect"


def _asset_resource_names(asset: dict) -> list[str]:
    return [str(name) for name in asset.get("meshNames", [])] + [
        str(name) for name in asset.get("textureNames", [])
    ]


def _effect_resource_names(asset: dict, effect: dict) -> list[str]:
    textures = asset.get("textureNames", [])
    meshes = asset.get("meshNames", [])
    names = [
        str(textures[int(index)]) for index in effect.get("textureIds", [])
        if 0 <= int(index) < len(textures)
    ]
    mesh_index = int(effect.get("meshIndex", -1))
    if 0 <= mesh_index < len(meshes):
        names.append(str(meshes[mesh_index]))
    return names


def _display_name(slug: str) -> str:
    return " ".join(word.capitalize() for word in slug.split("_") if word)


def _normalize_metadata(asset: dict, semantic_name: str) -> dict:
    normalized = json.loads(json.dumps(asset))
    title = _display_name(semantic_name)
    normalized["name"] = semantic_name
    normalized["displayName"] = title
    for sequence in normalized.get("sequences", []):
        sequence["name"] = title

    component_counts: Counter[str] = Counter()
    for effect in normalized.get("effects", []):
        base = _semantic_base(_effect_resource_names(normalized, effect))
        component_counts[base] += 1
        effect["name"] = "%s %02d" % (
            _display_name(base), component_counts[base])
    return normalized


def _load_manifest() -> dict[str, str]:
    if not NAME_PATH.exists():
        return {}
    payload = json.loads(NAME_PATH.read_text(encoding="utf-8"))
    names = payload.get("names", {})
    if not isinstance(names, dict):
        raise ValueError(f'invalid manifest:{NAME_PATH}')
    return {str(old).lower(): str(new).lower() for old, new in names.items()}


def _load_aliases() -> dict[str, str]:
    if not ALIAS_PATH.exists():
        return {}
    payload = json.loads(ALIAS_PATH.read_text(encoding="utf-8"))
    aliases = payload.get("aliases", {})
    if not isinstance(aliases, dict):
        raise ValueError(f'invalid record:{ALIAS_PATH}')
    return {str(old).lower(): str(new).lower() for old, new in aliases.items()}


def _build_names(assets: dict[str, dict], previous: dict[str, str]) -> dict[str, str]:
    names = dict(previous)
    used = set(names.values())
    counters: Counter[str] = Counter()
    for semantic in used:
        match = re.match(r"(.+)_([0-9]{3})$", semantic)
        if match:
            counters[match.group(1)] = max(counters[match.group(1)],
                                             int(match.group(2)))

    reverse = {semantic: legacy for legacy, semantic in names.items()}
    for current_name in sorted(assets):
        if current_name in reverse or current_name in names:
            continue
        if not PLACEHOLDER_RE.fullmatch(current_name):
            raise ValueError(f'asset without known identity:{current_name}')
        base = _semantic_base(_asset_resource_names(assets[current_name]))
        while True:
            counters[base] += 1
            semantic = f"{base}_{counters[base]:03d}"
            if semantic not in used:
                break
        names[current_name] = semantic
        used.add(semantic)
    return dict(sorted(names.items()))


def _rewrite_effect_names(value, aliases: dict[str, str]) -> int:
    changed = 0
    if isinstance(value, dict):
        effect_name = value.get("effectName")
        if isinstance(effect_name, str):
            canonical = aliases.get(effect_name.lower())
            if canonical is not None and canonical != effect_name:
                value["effectName"] = canonical
                changed += 1
        for child in value.values():
            changed += _rewrite_effect_names(child, aliases)
    elif isinstance(value, list):
        for child in value:
            changed += _rewrite_effect_names(child, aliases)
    return changed


def _data_reference_updates(aliases: dict[str, str]) -> tuple[dict[Path, str], int]:
    updates: dict[Path, str] = {}
    references = 0
    for path in DATA_DIR.rglob("*.json"):
        if EFFECT_ROOT in path.parents:
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        changed = _rewrite_effect_names(data, aliases)
        if changed:
            updates[path] = _json_text(data)
            references += changed
    return updates, references


def _write_atomic(path: Path, text: str) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    asset_paths = sorted(ASSET_DIR.glob("*.json"))
    assets = {
        path.stem.lower(): json.loads(path.read_text(encoding="utf-8"))
        for path in asset_paths
    }
    previous_names = _load_manifest()
    names = _build_names(assets, previous_names)
    reverse_names = {semantic: legacy for legacy, semantic in names.items()}
    if len(reverse_names) != len(names):
        raise ValueError('the proposal contains duplicate semantic names')

    old_aliases = _load_aliases()
    aliases = {legacy: semantic for legacy, semantic in names.items()}
    for legacy, target in old_aliases.items():
        aliases[legacy] = names.get(target, target)
    aliases = dict(sorted(aliases.items()))

    normalized_assets: dict[str, dict] = {}
    for current_name, asset in assets.items():
        legacy = reverse_names.get(current_name, current_name)
        semantic = names.get(legacy, current_name)
        if semantic in normalized_assets:
            raise ValueError(f'asset collision:{semantic}')
        normalized_assets[semantic] = _normalize_metadata(asset, semantic)

    missing_targets = sorted(set(aliases.values()) - normalized_assets.keys())
    if missing_targets:
        raise ValueError(f'aliases without destination:{missing_targets[:10]}')
    reference_updates, reference_count = _data_reference_updates(aliases)

    current_names = set(assets)
    target_names = set(normalized_assets)
    renamed = len(current_names - target_names)
    asset_updates = renamed + sum(
        assets[name] != normalized_assets[name]
        for name in current_names.intersection(target_names)
    )
    catalog_updates = previous_names != names or old_aliases != aliases
    print(f'Map assets:{len(normalized_assets)}')
    print(f"Assets a normalizar: {asset_updates} (renombres: {renamed})")
    print(f"Aliases legacy: {len(aliases)}")
    print(f'References to update:{reference_count} en {len(reference_updates)}files')
    for old, new in list(names.items())[:30]:
        print(f"  {old} -> {new}")
    if args.dry_run:
        return 0
    if not asset_updates and not catalog_updates and not reference_updates:
        print('No changes')
        return 0

    if STAGING_DIR.exists():
        shutil.rmtree(STAGING_DIR)
    if BACKUP_DIR.exists():
        raise ValueError(f"backup residual inesperado: {BACKUP_DIR}")
    staged_assets = STAGING_DIR / "mapeffects"
    staged_assets.mkdir(parents=True)
    for name, asset in normalized_assets.items():
        (staged_assets / f"{name}.json").write_text(
            _json_text(asset), encoding="utf-8")
    for path in ASSET_DIR.iterdir():
        if path.suffix.lower() == ".json":
            continue
        target = staged_assets / path.name
        if path.is_dir():
            shutil.copytree(path, target)
        else:
            shutil.copy2(path, target)

    aliases_payload = {
        "format": "Research map effect aliases",
        "aliases": aliases,
    }
    names_payload = {
        "format": "Research semantic map effect names",
        "names": names,
    }

    reference_backups = {
        path: path.read_bytes() for path in reference_updates
    }
    catalog_backups = {
        path: path.read_bytes() if path.exists() else None
        for path in (ALIAS_PATH, NAME_PATH)
    }
    try:
        ASSET_DIR.replace(BACKUP_DIR)
        staged_assets.replace(ASSET_DIR)
        CATALOG_DIR.mkdir(parents=True, exist_ok=True)
        _write_atomic(ALIAS_PATH, _json_text(aliases_payload))
        _write_atomic(NAME_PATH, _json_text(names_payload))
        for path, text in reference_updates.items():
            _write_atomic(path, text)
    except Exception:
        for path, payload in reference_backups.items():
            path.write_bytes(payload)
        for path, payload in catalog_backups.items():
            if payload is None:
                path.unlink(missing_ok=True)
            else:
                path.write_bytes(payload)
        if ASSET_DIR.exists():
            shutil.rmtree(ASSET_DIR)
        if BACKUP_DIR.exists():
            BACKUP_DIR.replace(ASSET_DIR)
        raise
    finally:
        if STAGING_DIR.exists():
            shutil.rmtree(STAGING_DIR)

    shutil.rmtree(BACKUP_DIR)
    print("Migracion publicada")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
