'Texture utilities shared by gltf_writer.py and converters\nof loose textures (copy_texture.py, prepare_wld_effects.py).\n\nFix "white bleed" on edges of textures with alpha clipping\n(alpha-cutout: grass, foliage, floor decos) when generating mipmaps. Cause:\nThe completely transparent pixels of these textures usually have RGB\nwhite (or some arbitrary fill color) below the alpha channel.\nA mipmap is generated by averaging blocks of NEIGHBOR pixels without respecting the\nalpha -- mixes that "invisible" white with the actual border color, and with\nALPHA_SCISSOR (clip, not blend) that contaminated average looks like a\nwhite halo/border right on the contour of the sprite, stronger the more\nfar (lower mip). Standard fix ("color bleeding"/dilation): before\ngenerate mipmaps, replace the RGB of each transparent pixel with the RGB\nof the nearest OPAQUE pixel, so that there is no hidden "white" that\nmix.\n\nWHEN YOU SHOULD NOT DO IT\n-------------------------\nIt only works if the alpha means "this is not part of the sprite". In many\ntextures the alpha means something ELSE and the pixels with alpha 0 look\nthe same: those of character equipment with AlphaBlendingMode "Glow" are the case\n-- its alpha is a brightness mask and is worth ~0 in almost the entire image,\nwhile the material makes them OPAQUE. Dilating there does not fix an edge:\nreplaces the entire image with the color of the handful of opaque texels,\nstretched out in a fan from wherever they are.\n\nMeasured on the 1,676 equipment textures in the dataset: 1,054 (63%) remained\nruined like that. It looked like "washed" armor with radial veins, and only\nin some pieces -- those that happened to have high alpha were saved.\n\nThat is why the debleed is OPT-IN: the caller knows if that texture is going to be\ncrop by alpha, and only there it corresponds.'

import numpy as np
from PIL import Image
from scipy.ndimage import distance_transform_edt


def load_rgba_debled(path, *, debleed: bool) -> Image.Image:
    'debleed=False returns the image as is, without dilation. See the note\n    above: on a texture that is not clipped by alpha, dilate destroys it.'
    img = Image.open(path).convert("RGBA")
    if not debleed:
        return img
    arr = np.array(img)
    alpha = arr[:, :, 3]
    opaque = alpha > 0

    if opaque.all() or not opaque.any():
        return img  # No visible source colour exists to propagate.

    _, indices = distance_transform_edt(~opaque, return_indices=True)
    arr[:, :, :3] = arr[:, :, :3][tuple(indices)]
    return Image.fromarray(arr, mode="RGBA")
